name: Continuous Integration

on:
  push:
    branches: [ main, trying, staging ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "build: Full build and integrated tests"
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v18
        with:
          install_url: https://releases.nixos.org/nix/nix-2.12.0/install
          nix_path: nixpkgs=channel:nixpkgs-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes recursive-nix ca-derivations
      - name: install tools
        run: |
          sudo -i nix-env -i $(nix build nixpkgs#direnv nixpkgs#sapling --no-link --print-out-paths)
      - name: clone buck2-nix.sl
        run: |
          sl clone https://github.com/${{ github.repository }} ${{ github.workspace }}/${{ github.event.repository.name }}.sl
          shopt -s dotglob
          mv ${{ github.workspace }}/${{ github.event.repository.name }}.sl/* .
      - name: direnv export
        uses: ./.github/actions/direnv
      - run: buck build ...
