name: Update Buck2

on:
  schedule:
    - cron: '0 2 * * *' # *-*-* 02:00:00 UTC
  workflow_dispatch: # manual trigger

jobs:
  build:
    name: "update: update buck2 nix expr"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
        with:
          extra-conf: |
            experimental-features = nix-command flakes recursive-nix ca-derivations

      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v1

      - name: update nix expression
        run: IS_CI=1 ./buck/nix/update.sh --buck2

      - name: build buck2
        run: |
          nix build --no-link --accept-flake-config ./buck/nix#packages/buck2

      - name: check and commit changes
        id: commit
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add buck/nix/buck2
          git commit -m "chore(buck2): update"

      - name: validate nix files changed
        if: steps.commit.outcome == 'success'
        run: |
          files=( $(git diff --name-only HEAD HEAD^ '*.nix') )
          echo "${#files[*]} nix files changed: ${files[*]}"
          if [[ "${#files[*]}" -ne 0 ]]; then
            nix-instantiate --parse "${files[@]}" >/dev/null
          fi

      - name: push changes
        if: steps.commit.outcome == 'success'
        uses: ad-m/github-push-action@0fafdd62b84042d49ec0cb92d9cac7f7ce4ec79e
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
